import { ArrowLeft, ArrowUpRight, FileText, FolderOpen, GitBranch, Link2, MoreHorizontal, Plus, Terminal } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export default function ProjectWorkspace() {
    const navigate = useNavigate();
    return <div className="mx-auto flex max-w-6xl flex-col gap-7">
        <button type="button" onClick={() => navigate('/')} className="flex w-fit items-center gap-2 font-mono text-xs font-bold text-text-muted hover:text-primary"><ArrowLeft size={14} /> ALL WORKSPACES</button>
        <header className="flex items-end justify-between gap-5 border-b-2 border-border-strong pb-6 max-md:flex-col max-md:items-start">
            <div><div className="mb-3 flex items-center gap-2 font-mono text-xs text-text-muted"><span className="size-2 bg-green" /> ACTIVE / LOCAL PROJECT</div><h1 className="text-4xl tracking-tight">orbit-desktop</h1><p className="mt-3 font-mono text-xs text-text-muted">~/Code/orbit · created 14 Mar 2026</p></div>
            <button className="btn btn-primary" type="button"><Terminal data-icon="inline-start" size={16} /> Open in VS Code</button>
        </header>
        <div className="grid gap-6 xl:grid-cols-[1fr_320px]">
            <div className="flex flex-col gap-6">
                <section className="panel p-5"><div className="mb-5 flex items-center justify-between"><h2 className="section-header mb-0">Project context</h2><button className="btn btn-ghost px-3 py-2 text-xs" type="button"><Plus data-icon="inline-start" size={14} /> Add context</button></div><div className="grid gap-3 md:grid-cols-2"><div className="card-compact flex items-center gap-3"><FileText size={17} className="text-primary" /><div><p className="font-space text-sm font-bold">frontend-architecture.md</p><p className="font-mono text-[10px] text-text-muted">docs / 4.2 KB / added 28m ago</p></div></div><div className="card-compact flex items-center gap-3"><FolderOpen size={17} className="text-purple" /><div><p className="font-space text-sm font-bold">src/components</p><p className="font-mono text-[10px] text-text-muted">directory / 24 files</p></div></div><div className="flex min-h-24 items-center justify-center border-2 border-dashed border-border-strong bg-white p-4 md:col-span-2"><p className="font-mono text-xs text-text-muted">Drop files, notes, or links here to build project context.</p></div></div></section>
                <section className="panel p-5"><div className="mb-5 flex items-center justify-between"><h2 className="section-header mb-0">Recent project activity</h2><MoreHorizontal size={17} /></div>{['Opened project in Orbit', 'Added frontend-architecture.md', 'Switched to feat/workspace-shell'].map((event, index) => <div className="flex items-center gap-4 border-t border-border-subtle py-4 first:border-t-0 first:pt-0" key={event}><span className="font-mono text-xs text-primary">0{index + 1}</span><p className="flex-1 font-space text-sm font-bold">{event}</p><span className="font-mono text-[10px] text-text-muted">{['12 MIN AGO', '28 MIN AGO', '1 HR AGO'][index]}</span></div>)}</section>
            </div>
            <aside className="flex flex-col gap-4"><section className="card-compact"><h2 className="section-header">Git status</h2><div className="flex items-center gap-3"><GitBranch size={17} className="text-primary" /><div><p className="font-mono text-sm font-bold">feat/workspace-shell</p><p className="font-mono text-[10px] text-text-muted">3 uncommitted changes</p></div></div></section><section className="card-compact"><h2 className="section-header">Connections</h2><div className="flex items-center justify-between border-b border-border-subtle py-3"><span className="flex items-center gap-2 font-space text-sm font-bold"><Link2 size={15} /> GitHub</span><span className="font-mono text-[10px] text-green">READY</span></div><div className="flex items-center justify-between py-3"><span className="flex items-center gap-2 font-space text-sm font-bold"><Link2 size={15} /> VS Code</span><span className="font-mono text-[10px] text-green">READY</span></div><button type="button" onClick={() => navigate('/integrations')} className="mt-3 flex items-center gap-2 font-mono text-xs font-bold text-text-muted hover:text-primary">MANAGE <ArrowUpRight size={13} /></button></section></aside>
        </div>
    </div>;
}
